In [2]:
import cv2
import numpy as np

PATH = "test\\jfif\\the_rock.jfif"
img = cv2.imread(PATH)
cv2.imshow('image', img)
cv2.waitKey(0) # waits until a key is pressed
#cv2.destroyAllWindows()

[[[228 190 158]
  [225 188 154]
  [225 188 154]
  ...
  [184 156 155]
  [181 153 152]
  [181 153 152]]

 [[230 192 160]
  [227 189 155]
  [226 188 154]
  ...
  [182 154 153]
  [182 154 153]
  [180 152 152]]

 [[232 194 162]
  [227 189 155]
  [230 191 153]
  ...
  [185 157 156]
  [181 153 153]
  [182 154 154]]

 ...

 [[162 127 124]
  [162 125 121]
  [160 122 118]
  ...
  [208 207 216]
  [127 126 135]
  [104 106 116]]

 [[164 127 123]
  [156 118 114]
  [160 122 118]
  ...
  [232 241 245]
  [188 194 199]
  [ 91  96  97]]

 [[164 127 123]
  [159 121 117]
  [158 120 116]
  ...
  [209 212 220]
  [192 195 200]
  [ 90  91  95]]]
